@OrderService_HostAddress = http://localhost:5087

###
### Submit Order  
POST {{OrderService_HostAddress}}/orders  
Content-Type: application/json  

{  
 "OrderId": "12345",  
 "ProductName": "Sample Product",  
 "Quantity": 1,  
 "Price": 100.0  
}

### Get order status by ID  
GET {{OrderService_HostAddress}}/orders/{{orderId}}  
Content-Type: application/json  

### Get all orders  
GET {{OrderService_HostAddress}}/orders/getAll  
Content-Type: application/json